ahmad syukron
bold-fox-2018/fancy-todo pull request #8
Opened 2019-03-11 01:20 UTC by sirdanke

2019-03-11 01:42 UTC, sirdanke commented
JWTTOKEN=RAHASIADONG

2019-03-18 06:25 UTC, dmtrxw requested changes

2019-03-18 06:25 UTC, dmtrxw commented on server/routes/user.js
> +router.get('/projectTodo/:email',access, projectController.findWhere)
Router bisa dibikin lebih rapi, pisah per contextnya aja. Misalkan:
- `/todos`, buat CRUD todo
- `/projects/:id/todos`, buat CRUD todo yang ada di project
- `/auth`, buat authentication/authorization
- dll

Jadi ga semuanya dicampur di 1 file ini.

2019-03-18 06:25 UTC, dmtrxw commented on server/helpers/sendEmail.js
> +            user: "ahmad.syukron6991@gmail.com",
Ini juga pake environment variable, gw ngirimnya atas nama lu dong (+ gw harus tau password lu)

2019-03-18 06:25 UTC, dmtrxw commented on server/controller/projectController.js
> +                return Projects
Gw pusing ngeliat query2nya, bisa lebih rapi seharusnya

2019-03-18 06:25 UTC, dmtrxw commented on client/index.js
> +        $.post('http://localhost:3000/verify', { token: localStorage.getItem('token') })
URL ke server simpen di global variable

2019-03-18 06:26 UTC, closed without merging